[package]
name = "eliduprees-web-games-lib"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
nalgebra = {version = "0.16", features = ["serde-serialize"]}
rand = "0.7"
